spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthSport?useUnicode=true&characterEncoding=utf-8
    username: root
    password: luo123456


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: org.jxgm.health.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 9090